# Generated by Django 3.0.7 on 2020-06-23 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('EU', 'Awaiting Email'), ('ES', 'Email Sent'), ('PC', 'Project Completed'), ('IN', 'Inactive'), ('AR', 'Archived')], default='EU', max_length=2),
        ),
    ]
