# Generated by Django 3.0.7 on 2020-07-13 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_quote_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='status',
        ),
    ]
