# Generated by Django 3.0.7 on 2020-07-13 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_auto_20200713_1434'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quotestatus',
            options={'verbose_name_plural': 'Quote - Statuses'},
        ),
        migrations.AddField(
            model_name='quote',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='quotes.QuoteStatus'),
            preserve_default=False,
        ),
    ]
