# Generated by Django 3.0.7 on 2020-07-23 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0006_auto_20200714_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwningType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Awning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awning_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quotes.AwningType')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quotes.Quote')),
            ],
        ),
    ]
