# Generated by Django 3.0.7 on 2020-08-10 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0007_awning_awningtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabric_color', models.CharField(max_length=20)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quotes.Quote')),
            ],
        ),
    ]
