# Generated by Django 3.0.7 on 2020-08-13 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0008_screen'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwningMotor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('awning', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='quotes.Awning')),
            ],
        ),
    ]
