# Generated by Django 3.0.7 on 2020-08-17 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0009_awningmotor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AwningMotor',
        ),
    ]
