# Generated by Django 3.0.7 on 2020-08-17 23:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0010_delete_awningmotor'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwningBracketType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AwningCordLength',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AwningCrankSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AwningHoodCover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AwningMotorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AwningMount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AwningOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AwningRemote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AwningValance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='awning',
            name='additional_costs_quote',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='awning',
            name='awning_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='awning',
            name='awning_price_quote',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='awning',
            name='bracket_color',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='awning',
            name='bracket_price_quote',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='awning',
            name='bracket_quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='awning',
            name='control_notes',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='awning',
            name='control_side',
            field=models.IntegerField(choices=[(None, '(Unknown)'), (0, 'Left'), (1, 'Right')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='awning',
            name='fabric',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='awning',
            name='frame_color',
            field=models.CharField(default='white', max_length=30),
        ),
        migrations.AddField(
            model_name='awning',
            name='height_inches',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='awning',
            name='motor_price_quote',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='awning',
            name='mount_notes',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='awning',
            name='placement_on_house',
            field=models.IntegerField(choices=[(None, '(Unknown)'), (0, 'Front'), (1, 'Back'), (2, 'Right Side'), (3, 'Left Side')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='awning',
            name='projection_inches',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='awning',
            name='trim',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='awning',
            name='width_inches',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='awning',
            name='wind_sensor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='awning',
            name='wrap_front_profile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='awning',
            name='bracket_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='quotes.AwningBracketType'),
        ),
        migrations.AddField(
            model_name='awning',
            name='cord_length',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='quotes.AwningCordLength'),
        ),
        migrations.AddField(
            model_name='awning',
            name='crank_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='quotes.AwningCrankSize'),
        ),
        migrations.AddField(
            model_name='awning',
            name='hood_cover',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='quotes.AwningHoodCover'),
        ),
        migrations.AddField(
            model_name='awning',
            name='motor_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='quotes.AwningMotorType'),
        ),
        migrations.AddField(
            model_name='awning',
            name='mount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='quotes.AwningMount'),
        ),
        migrations.AddField(
            model_name='awning',
            name='operation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='quotes.AwningOperation'),
        ),
        migrations.AddField(
            model_name='awning',
            name='remote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='quotes.AwningRemote'),
        ),
        migrations.AddField(
            model_name='awning',
            name='valance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='quotes.AwningValance'),
        ),
    ]
