# Generated by Django 3.0.7 on 2020-08-19 19:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0012_auto_20200819_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='awningtype',
            name='can_set_height',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='awningtype',
            name='can_wrap_front_profile',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='awning',
            name='bracket_quantity',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='quote',
            name='install_difficulty',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='quote',
            name='installers_required',
            field=models.PositiveIntegerField(),
        ),
    ]
