# Generated by Django 3.0.7 on 2020-08-19 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0014_auto_20200819_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='customers',
        ),
        migrations.AddField(
            model_name='customer',
            name='quote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='quotes.Quote'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
