# Generated by Django 3.0.7 on 2020-09-02 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0015_auto_20200819_1607'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quote',
            options={'permissions': [('view_all_quotes', 'Can view all quotes from every user')]},
        ),
    ]
