# Generated by Django 3.0.7 on 2020-09-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0016_auto_20200902_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='last_emailed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
